version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/localapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=walnut16@
    networks:
      - profile-mysql-network
  mysqldb:
    image: mysql:8.0
    ports:
      - 3308:3308
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=walnut16@
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - profile-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data:
networks:
  profile-mysql-network:
    name: profile-mysql-network